// <auto-generated />
namespace ScoreboardSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ScoreFixTwo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ScoreFixTwo));
        
        string IMigrationMetadata.Id
        {
            get { return "201412070443474_ScoreFixTwo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
