// <auto-generated />
namespace ScoreboardSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DepartmentStoredProcedure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DepartmentStoredProcedure));
        
        string IMigrationMetadata.Id
        {
            get { return "201412060545440_DepartmentStoredProcedure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
